### PR TITLE
Fix bars not connecting

### LINKED ISSUE #172: BUG: Iron bars not connecting
**Describe the bug**
Iron bars should connect to adjacent blocks.

**Expected behavior**
image

**Screenshots**
image

### PR DESCRIPTION
**Pull request by iquelli**
Closes #172

### CODE REVIEW

File: src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitWorldEditor.java [hunk 1]
```diff
@@ -131,6 +135,37 @@ public static void clearDirtFromMazePart(Location upperCorner, Location lowerCor
...
         fill(upperCorner, lowerCorner, Material.IRON_BARS);
+        connectBars(upperCorner, lowerCorner);
+    }
+
+    private static void connectBars(Location upperCorner, Location lowerCorner) {
+        for (int x = lowerCorner.getBlockX(); x <= upperCorner.getBlockX(); x++) {
+            for (int y = lowerCorner.getBlockY(); y <= upperCorner.getBlockY(); y++) {
+                for (int z = lowerCorner.getBlockZ(); z <= upperCorner.getBlockZ(); z++) {
+                    Location currentLocation = new Location(lowerCorner.getWorld(), x, y, z);
+                    BlockData bd = Bukkit.createBlockData("minecraft:iron_bars");
```
Comment (TiagoFar78) [inline src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitWorldEditor.java:146]: Instead of this declare block above currentLocation.getBlock() and then use block.getData() or something like that.

File: src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitWorldEditor.java [hunk 2]
```diff
@@ -131,6 +135,37 @@ public static void clearDirtFromMazePart(Location upperCorner, Location lowerCor
...
+
+                    if (bd instanceof MultipleFacing) {
```
Comment (TiagoFar78) [inline src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitWorldEditor.java:148]: I don't think you need this if. Iron bars are being created immediately before this call.

**Review by TiagoFar78 — APPROVED** [review]

File: src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitWorldEditor.java (hunk 1 above)
Comment (iquelli) [reply src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitWorldEditor.java:146]: block.getData() shows as deprecated
